import os
from pptx import Presentation
from pptx.util import Inches, Pt

class PPTXOutputGenerator:
    def __init__(self, output_dir: str):
        self.output_dir = output_dir

    def generate(self, content: any, filename: str, metadata: dict = None) -> dict:
        try:
            target_path = os.path.join(self.output_dir, f"{filename}.pptx")
            prs = Presentation()

            title = metadata.get("title", "Presentation") if metadata else "Presentation"
            
            # Title slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            title_shape = slide.shapes.title
            subtitle = slide.placeholders[1]
            title_shape.text = title
            subtitle.text = "Generated by Sovereign"

            # Content slide
            bullet_slide_layout = prs.slide_layouts[1]
            slide2 = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide2.shapes
            title_shape2 = shapes.title
            body_shape = shapes.placeholders[1]

            title_shape2.text = "Overview"
            tf = body_shape.text_frame

            text_content = str(content)
            paragraphs = [p for p in text_content.split('\n') if p.strip()]
            
            for i, p in enumerate(paragraphs[:5]): # simple presentation of first 5 paragraphs
                if i == 0:
                    tf.text = p.strip()
                else:
                    p_shape = tf.add_paragraph()
                    p_shape.text = p.strip()

            prs.save(target_path)
            return {"status": "success", "path": target_path, "filename": f"{filename}.pptx"}
        except Exception as e:
            return {"status": "error", "errors": [str(e)]}
