from typing import Dict, Any, List
from .interface import OutputGeneratorInterface

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
except ImportError:
    Presentation = None

class PPTXOutputGenerator(OutputGeneratorInterface):
    """Generates PowerPoint presentations (.pptx) from structured content."""
    def generate(self, content: Any, filename: str, metadata: Dict[str, Any] = None) -> Dict[str, Any]:
        if Presentation is None:
            return {
                "status": "failed",
                "format": "pptx",
                "errors": ["python-pptx is not installed."],
                "metadata": metadata or {}
            }

        if not filename.endswith('.pptx'):
            filename += '.pptx'

        safe_path = self._get_safe_path(filename)
        metadata = metadata or {}

        try:
            prs = Presentation()
            blank_slide_layout = prs.slide_layouts[1]  # Title and Content layout

            # Title Slide
            title_slide_layout = prs.slide_layouts[0]
            title_slide = prs.slides.add_slide(title_slide_layout)
            title = title_slide.shapes.title
            subtitle = title_slide.placeholders[1]
            title.text = metadata.get("title", "Sovereign Executive Report")
            subtitle.text = "Generated by Sovereign Local AI Workbench"

            # Process slides
            if isinstance(content, dict):
                for section_title, section_body in content.items():
                    slide = prs.slides.add_slide(blank_slide_layout)
                    slide.shapes.title.text = str(section_title)
                    body_shape = slide.placeholders[1]
                    tf = body_shape.text_frame
                    tf.text = str(section_body)
            elif isinstance(content, list):
                for item in content:
                    slide = prs.slides.add_slide(blank_slide_layout)
                    slide.shapes.title.text = "Analysis Item"
                    body_shape = slide.placeholders[1]
                    body_shape.text_frame.text = str(item)
            else:
                # Text content: split by headers if available
                text = str(content)
                paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
                for idx, p in enumerate(paragraphs[:8]):  # Up to 8 slides
                    slide = prs.slides.add_slide(blank_slide_layout)
                    slide.shapes.title.text = f"Slide {idx + 1}"
                    body_shape = slide.placeholders[1]
                    body_shape.text_frame.text = p

            prs.save(safe_path)

            return {
                "status": "success",
                "format": "pptx",
                "path": safe_path,
                "filename": filename,
                "metadata": metadata
            }
        except Exception as e:
            return {
                "status": "failed",
                "format": "pptx",
                "errors": [str(e)],
                "metadata": metadata
            }
